//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPointsTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverID { get; set; }
        public string DriverNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DriverType { get; set; }
        public Nullable<decimal> EmployeePayPct { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string TextMessage { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyPhone { get; set; }
        public string SSNum { get; set; }
        public string DOB { get; set; }
        public string CDLNum { get; set; }
        public Nullable<System.DateTime> CDLExpiration { get; set; }
        public Nullable<System.DateTime> MedicalExpiration { get; set; }
        public Nullable<System.DateTime> TWICExpiration { get; set; }
        public Nullable<System.DateTime> AnnualReview { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string ResignReason { get; set; }
        public Nullable<bool> Rehire { get; set; }
        public string FuelCardNum { get; set; }
        public string Notes { get; set; }
        public string TruckNum { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
