//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPointsTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int ID { get; set; }
        public string Driver { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> PayPeriodStart { get; set; }
        public Nullable<System.DateTime> PayPeriodEnd { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Fuel { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
