//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPointsTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MondayDate { get; set; }
        public string Driver { get; set; }
        public string MondayLocal { get; set; }
        public string MondayRegional { get; set; }
        public string TuesdayLocal { get; set; }
        public string TuesdayRegional { get; set; }
        public string WednesdayLocal { get; set; }
        public string WednesdayRegional { get; set; }
        public string ThursdayLocal { get; set; }
        public string ThursdayRegional { get; set; }
        public string FridayLocal { get; set; }
        public string FridayRegional { get; set; }
        public string SaturdayLocal { get; set; }
        public string SaturdayRegional { get; set; }
        public string SundayLocal { get; set; }
        public string SundayRegional { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
