//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPointsTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesDriverPay
    {
        public int ID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> ToDispatch { get; set; }
        public Nullable<bool> ActiveLeg { get; set; }
        public string TypeOfLoad { get; set; }
        public string PayType { get; set; }
        public string DispatchNotes { get; set; }
        public Nullable<System.DateTime> ApptTime { get; set; }
        public Nullable<System.DateTime> DetentionStarts { get; set; }
        public string DepartTime { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<decimal> LineHaulAmountTruck { get; set; }
        public Nullable<decimal> FSAmountTruck { get; set; }
        public Nullable<decimal> TotalAmountTruck { get; set; }
        public Nullable<decimal> TotalAmountEmployee { get; set; }
        public string Driver { get; set; }
        public Nullable<int> DriverRowID { get; set; }
        public string DriverType { get; set; }
        public string TruckNum { get; set; }
        public Nullable<decimal> TruckPayPct { get; set; }
        public Nullable<decimal> FSDeductionPct { get; set; }
        public Nullable<decimal> EmployeePayPct { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> PrePlanSent { get; set; }
        public string DispatchAcceptedStatus { get; set; }
        public Nullable<bool> WayBilled { get; set; }
        public Nullable<bool> PayDriver { get; set; }
        public Nullable<bool> Outgate { get; set; }
        public Nullable<bool> Ingate { get; set; }
        public Nullable<bool> POD { get; set; }
        public Nullable<bool> BOL { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<bool> DriverPaid { get; set; }
        public Nullable<bool> CommissionPaid { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
