//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPointsTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDispatch_Progress
    {
        public Nullable<int> WorkOrder { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public string Pro { get; set; }
        public string Container1 { get; set; }
        public Nullable<bool> ToDispatch { get; set; }
        public string Status { get; set; }
        public string leg { get; set; }
        public int WorkOrderID { get; set; }
    }
}
